# .github/workflows/reusable-test.yml

name: Reusable Python CI

on:
    workflow_call:
        inputs:
            python-version:
                type: string
                default: '3.12'
        secrets:
            DEPLOY_KEY:
                required: false

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v7.0.0

            - name: generate tag
              id: build
              run: echo "tag=build-${{ github.sha }}" >> $GITHUB_OUTPUT
            
            - name: install uv
              uses: astral-sh/setup-uv@v8.2.0
              with:
                  enable-cache: true
                  cache-dependency-glob: 'uv.lock'
                  python-version: ${{ inputs.python-version }}

            - name: Install dependency
              run: uv sync --all-extras --dev

            - name: Run tests
              run: uv run pytest --html=report.html

            - name: upload artifacts
              uses: action/upload-artifacts@v7.0.2
              if: always()
              with:
                   name: test-reports-${{ step.build.output.tag }}
                   path: report.html